### ISSUE TITLE
fix: accessibility

### ISSUE THREAD

**Issue by nstksean** [nstksean/doeYu#17]
- [x] Improve accessibility 
- [x] Add CTA (call to action)

**Comment by nstksean** [comment]
[c6acda9](https://github.com/nstksean/doeYu/pull/21/commits/c6acda98631c9066e83fb573afbeb38d9ce9742e)
solve

**Comment by lucifiel0121** [comment]
no info, plz add.

**Comment by nstksean** [comment]
close with #26
