### ISSUE TITLE
bug: layout issue 

### ISSUE THREAD

**Issue by lucifiel0121** [nstksean/doeYu#34]
![截圖 2022-10-30 下午3 04 38](https://user-images.githubusercontent.com/13078450/198866644-e1b9b3ee-710a-45da-b163-a220216b3be0.png)

**Comment by nstksean** [comment]
可以稍微敘述一下問題嗎？

**Comment by lucifiel0121** [comment]
layout issue. 我有畫線 看得到那個區域嗎

你花 ３０分鐘找，還是真的找不到再跟我說
再來開 zoom 看是什麼問題
