### ISSUE TITLE
bug: CityStack layout break in iphone

### ISSUE THREAD

**Issue by nstksean** [nstksean/doeYu#38]
- [x] 城市 Stack container 於 safari 瀏覽器上顯示跑版

**Comment by lucifiel0121** [comment]
layout Issue 圖呢?

**Comment by nstksean** [comment]
補上 Layout issue
Safari 瀏覽器在 Mac 及 Iphone 
<img width="450" alt="截圖 2022-11-14 上午9 32 13" src="https://user-images.githubusercontent.com/101794104/201557403-5858cb8e-b214-4a9c-b559-258a6f06b642.png">
