### ISSUE TITLE
fix route not works

### ISSUE THREAD

**Issue by lucifiel0121** [nstksean/doeYu#5]
10/17 會議後新增：
TravelSpot 區

- [x] Card 可點擊跳轉

Stack區

posts/location

- [x] 首頁 banner 可以點擊轉跳
- [x] 點進該城市，顯示該城市的特有內容。
即可以點選照片轉跳 
`https://nextjs.org/docs/routing/dynamic-routes`

- [x] hover should have cursor
![截圖 2022-10-13 下午10 14 10](https://user-images.githubusercontent.com/13078450/195621665-d51a80dd-f850-43f7-ab8d-5c3b9cd4b5f3.png)

posts/restaurant

- [x] 美食 可以點擊轉跳

**Comment by nstksean** [comment]
謝勳 馬上改。
