### ISSUE TITLE
fix:  RWD mobile issue

### ISSUE THREAD

**Issue by lucifiel0121** [nstksean/doeYu#6]
- [x] RWD 做 768以上
- [x] RWD 做兩種 0-768(375 為基準）

**Comment by nstksean** [comment]
#11  Make UI follow the design
# PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our [guidelines](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit
):
 - [X] Tests for the changes have been added (for bug fixes / features)
 - [X] Docs have been added / updated (for bug fixes / features)
# PR Type
What kind of change does this PR introduce?

 - [ ] Bugfix
 - [X] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Documentation content changes
- [ ] Other... Please describe:

# What is the current behavior?
[95042ab](https://github.com/nstksean/doeYu/pull/11/commits/95042ab41b5467174ac73eb9bfcc21d8424d0435)

# What is the new behavior?
enhance RWD feature for under 768px.

# Does this PR introduce a breaking change?
 - [ ] Yes
 - [X] No
# Other information
